### PR TITLE
Dev partial detailing

### PR DESCRIPTION
**Pull request by oshliaer**
The next code works fine

```js
(function logGlobs(env){
  var res = [];
  for(var e in env){
    if(!this.hasOwnProperty(e))
      res.push(e);
  }
  Logger.log('\n' + res.sort().join(": false,\n") + ': false')
})(this);
```

## Logs

> [18-09-19 18:56:24:370 MSK] 
> BigNumber: false,
> Browser: false,
> CacheService: false,
> CalendarApp: false,
> CardService: false,
> Charts: false,
> ContactsApp: false,
> ContentService: false,
> DocumentApp: false,
> DriveApp: false,
> ErrorService: false,
> FormApp: false,
> GmailApp: false,
> GroupsApp: false,
> HomeroomService: false,
> HtmlService: false,
> Jdbc: false,
> LanguageApp: false,
> LinearOptimizationService: false,
> LockService: false,
> Logger: false,
> MailApp: false,
> Maps: false,
> MimeType: false,
> PropertiesService: false,
> ScriptApp: false,
> ScriptProperties: false,
> Session: false,
> SitesApp: false,
> SlidesApp: false,
> SoapService: false,
> SpreadsheetApp: false,
> UiApp: false,
> UrlFetchApp: false,
> UserProperties: false,
> Utilities: false,
> Xml: false,
> XmlService: false,
> console: false

### CODE REVIEW

**Comment by selectnull** [comment]
@oshliaer thank you, I'll look into it over the weekend and merge it if it checks out.

**Comment by selectnull** [comment]
@oshliaer Thank you very much for the contribution, it's very welcomed and I will gladly merge it if you address these points:

* There's no need to ignore node_modules, please remove it from 2114fd78bf9d4150a549fc1114b29064797ce9f6
* some of the services you've added in 506184a4366901585b9f96cd9563e53ccf0cbf8a are not documented or deprecated and (IMHO) as such should not be part of this plugin. please remove those:
    * ErrorService - not documented
    * HomeroomService - not documented
    * ScriptProperties - deprecated
    * SoapService - not documented
    * UiApp - deprecated
    * UserProperties - deprecated
    * Xml - not documented
    * console - not documented (and as far as I know, Logger should be used instead)

**Comment by oshliaer** [comment]
- [x] node_modules
- [x] ErrorService
- [x] HomeroomService
- [x] ScriptProperties
- [x] SoapService
- [x] UiApp
- [x] UserProperties
- [x] Xml
- [x] console

**Comment by oshliaer** [comment]
@selectnull Thank you for the clarification. I understood something new for me.

It seems eslint doesn't have a rule for marking deprecated globals.

**Comment by oshliaer** [comment]
@selectnull 

Does it make sense to wait yet?

**Comment by selectnull** [comment]
Hey @oshliaer 

I've merged and published your changes.  So sorry it took so long, I simply forgot about it.

Thank you for the contributions and I'll be more responsive next time :)

**Comment by oshliaer** [comment]
Thanks!

**Pull request merged**
