### PR TITLE
Added GoogleAppsScript global namespace

### PR DESCRIPTION
**Pull request by jakeleventhal**
Screenshot 2023-05-30 at 2 58 52 PM
Fixes this issue^

### CODE REVIEW

**Comment by jakeleventhal** [comment]
ping @selectnull

**Comment by selectnull** [comment]
Hi @jakeleventhal, 

can you provide me with a link to GAS documentation that shows where this GoogleAppsScript objects is defined?
I haven't used GAS in a very long time and the docs are kind of confusing to me at this point.

If you send me a link that clearly shows this GoogleAppsScript object should be defined, I'll quickly merge the PR and publish it. Thanks.

**Comment by jakeleventhal** [comment]
> Hi @jakeleventhal,
> 
> can you provide me with a link to GAS documentation that shows where this GoogleAppsScript objects is defined? I haven't used GAS in a very long time and the docs are kind of confusing to me at this point.
> 
> If you send me a link that clearly shows this GoogleAppsScript object should be defined, I'll quickly merge the PR and publish it. Thanks.

https://github.com/google/clasp/blob/551000b55565d20fccc29673c5460022d42ee5cf/docs/typescript.md?plain=1#L183

**Comment by jakeleventhal** [comment]
@selectnull were you looking for something else

**Comment by selectnull** [comment]
@jakeleventhal I was looking for a reference in GAS documentation.

I haven't used GAS for years and I'm not really sure what belongs to this project. I would like it to be useful, as I see that people still use it. At the same time, I'd like to be sure that what I merge is really used.

Please help me understand how this is being used in development, by providing me links to official documentation that helps me understand why this needs to be added.

Thanks.

**Comment by jakeleventhal** [comment]
@selectnull i am using apps-scripts to access google sheets data via an apps script.
`@types/google-apps-script` is the package that provides the typings that i linked to.

Screenshot 2023-06-07 at 3 06 49 PM
This screenshot shows how I am actually accessing the sheet, using clasp. As you can see, the inferred type is `GoogleAppsScript.Spreadsheet.Sheet`


The typings themselves are not going to show up in documentation, because the TypeScript types are only defined as developer utilities in that package (where I linked). However, [this link](https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet-app#getactivespreadsheet) shows the `getActiveSpreadsheet` code. You can see that it returns "Spreadsheet", but it is namespaced under `GoogleAppsScript`

**Comment by selectnull** [comment]
@jakeleventhal Thank you for the contribution and especially for patience and helping me understand why was this needed.
I've merged the PR and published the changes to npm.

**Pull request merged**
